import type { Metadata } from "next";
import Header from "./components/header"
import Footer from "./components/footer"
import localFont from "next/font/local";

import "./globals.css";

import { Inter } from "next/font/google"
import React from "react";

const geistSans = localFont({
  
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio Site",
  description: "Generated by Naseer Ahmed Wighio",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Header/>
        <script/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
